# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSql11():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sql11(self):
    self.driver.get("https://www.offices355.com/vulnerabilities/sqli/")
    self.driver.set_window_size(1378, 674)
    self.driver.find_element(By.NAME, "id").click()
    self.driver.find_element(By.NAME, "id").send_keys("1")
    self.driver.find_element(By.NAME, "Submit").click()
  
